name: pr-checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - ".github/**"
      - "build.zig"
      - "build.zig.zon"
      - "src/**"
      - "vendor/**"
      - "Makefile"
  workflow_dispatch:

jobs:
  zig-fmt:
    name: zig fmt

    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Zig version used from the `minimum_zig_version` field in build.zig.zon
      - uses: mlugg/setup-zig@v2

      - name: Run zig fmt
        id: fmt
        run: |
          zig fmt --check ./*.zig ./**/*.zig 2> zig-fmt.err > zig-fmt.err2 || echo "Failed"
          delimiter="$(openssl rand -hex 8)"
          echo "zig_fmt_errs<<${delimiter}" >> "${GITHUB_OUTPUT}"

          if [ -s zig-fmt.err ]; then
            echo "// The following errors occurred:" >> "${GITHUB_OUTPUT}"
            cat zig-fmt.err >> "${GITHUB_OUTPUT}"
          fi

          if [ -s zig-fmt.err2 ]; then
            echo "// The following files were not formatted:" >> "${GITHUB_OUTPUT}"
            cat zig-fmt.err2 >> "${GITHUB_OUTPUT}"
          fi

          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      - name: Fail the job
        if: steps.fmt.outputs.zig_fmt_errs != ''
        run: exit 1

  compile-check:
    name: compile check

    if: github.event.pull_request.draft == false

    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: ./.github/actions/install
        with:
          os: linux
          arch: x86_64

      - name: Build snapshot
        run: zig build -Dprebuilt_v8_path=v8/libc_v8.a -Doptimize=ReleaseFast snapshot_creator -- src/snapshot.bin

      - name: Compile check
        run: zig build -Dsnapshot_path=../../snapshot.bin -Dprebuilt_v8_path=v8/libc_v8.a -Doptimize=ReleaseFast -Dcpu=x86_64 -Dgit_commit=$(git rev-parse --short ${{ github.sha }})
